export const COMMAND_CATALOG = [
  { name:'pwd', category:'file management', syntax:'pwd', examples:['pwd'], explanation:'Print the absolute path of your current working directory.', warning:'Safe command.', safety:'safe', related:['ls','cd'] },
  { name:'ls', category:'file management', syntax:'ls [options] [path]', examples:['ls','ls -la','ls /etc'], explanation:'List directory contents. Use -l for details and -a for hidden entries.', warning:'Safe command.', safety:'safe', related:['pwd','cd','find'] },
  { name:'cd', category:'file management', syntax:'cd [directory]', examples:['cd /home','cd ..','cd ~'], explanation:'Change the current working directory.', warning:'Safe in normal use. Know where you are before running file-changing commands.', safety:'safe', related:['pwd','ls'] },
  { name:'mkdir', category:'file management', syntax:'mkdir [-p] <directory>', examples:['mkdir projects','mkdir -p work/linux/labs'], explanation:'Create directories. -p also creates missing parent directories.', warning:'Safe command when used in paths you own.', safety:'safe', related:['rmdir','cd'] },
  { name:'touch', category:'file management', syntax:'touch <file>', examples:['touch notes.txt','touch script.sh'], explanation:'Create an empty file or update its timestamp.', warning:'Safe, but touching an existing file changes its timestamp.', safety:'safe', related:['cat','nano'] },
  { name:'cat', category:'file management', syntax:'cat <file>', examples:['cat README.md','cat /etc/hosts'], explanation:'Print file contents to the terminal.', warning:'Usually safe. Avoid dumping huge or binary files into a terminal.', safety:'safe', related:['less','head','tail'] },
  { name:'head', category:'file management', syntax:'head [-n N] <file>', examples:['head notes.txt','head -n 20 app.log'], explanation:'Show the first lines of a text file.', warning:'Safe command.', safety:'safe', related:['tail','cat'] },
  { name:'tail', category:'file management', syntax:'tail [-n N] <file>', examples:['tail notes.txt','tail -n 50 app.log'], explanation:'Show the last lines of a text file.', warning:'Safe command.', safety:'safe', related:['head','journalctl'] },
  { name:'cp', category:'file management', syntax:'cp [options] source destination', examples:['cp notes.txt backup.txt','cp -r project project-copy'], explanation:'Copy files or directories.', warning:'Medium risk because an existing destination can be overwritten.', safety:'medium', related:['mv','rsync'] },
  { name:'mv', category:'file management', syntax:'mv source destination', examples:['mv draft.txt final.txt','mv notes.txt archive/'], explanation:'Move or rename files and directories.', warning:'Medium risk because an existing destination can be replaced.', safety:'medium', related:['cp','rm'] },
  { name:'rm', category:'file management', syntax:'rm [options] <path>', examples:['rm old.txt','rm -r old-folder'], explanation:'Remove files or directories.', warning:'High risk. Deletion is normally permanent; inspect the target first.', safety:'high', related:['find','ls'] },
  { name:'find', category:'file management', syntax:'find [path] -name <pattern>', examples:['find . -name "*.log"','find /tmp -name cache'], explanation:'Search the filesystem by path, name, type and other properties.', warning:'Safe when searching. Actions such as -delete increase risk.', safety:'safe', related:['grep','which'] },
  { name:'grep', category:'file management', syntax:'grep [options] pattern [file]', examples:['grep error app.log','grep -i linux notes.txt'], explanation:'Search text for matching lines.', warning:'Safe command when only reading files.', safety:'safe', related:['find','cat'] },
  { name:'du', category:'monitoring', syntax:'du [options] [path]', examples:['du -sh .','du -h /var/log'], explanation:'Estimate file and directory disk usage.', warning:'Safe command.', safety:'safe', related:['df','ls'] },
  { name:'df', category:'monitoring', syntax:'df [options]', examples:['df -h'], explanation:'Show filesystem capacity and free disk space.', warning:'Safe command.', safety:'safe', related:['du','lsblk'] },
  { name:'stat', category:'file management', syntax:'stat <path>', examples:['stat script.sh'], explanation:'Show detailed metadata for a file or directory.', warning:'Safe command.', safety:'safe', related:['ls','chmod'] },
  { name:'chmod', category:'permissions', syntax:'chmod <mode> <path>', examples:['chmod 755 script.sh','chmod 644 notes.txt','chmod +x deploy.sh'], explanation:'Change read, write and execute permissions.', warning:'High risk when overly broad permissions such as 777 are used.', safety:'high', related:['chown','stat','sudo'] },
  { name:'chown', category:'permissions', syntax:'chown [owner][:group] <path>', examples:['sudo chown alice:dev app.conf'], explanation:'Change file ownership.', warning:'High risk because wrong ownership can break services or access.', safety:'high', related:['chmod','id','sudo'] },
  { name:'sudo', category:'permissions', syntax:'sudo <command>', examples:['sudo apt update','sudo systemctl restart nginx'], explanation:'Run a command with elevated privileges.', warning:'High risk. Verify the exact command and target before pressing Enter.', safety:'high', related:['id','chmod','systemctl'] },
  { name:'whoami', category:'permissions', syntax:'whoami', examples:['whoami'], explanation:'Print the current effective username.', warning:'Safe command.', safety:'safe', related:['id','groups'] },
  { name:'id', category:'permissions', syntax:'id [user]', examples:['id','id alice'], explanation:'Show user and group identifiers.', warning:'Safe command.', safety:'safe', related:['whoami','groups'] },
  { name:'ps', category:'monitoring', syntax:'ps [options]', examples:['ps aux','ps -ef'], explanation:'List running processes.', warning:'Safe command when only inspecting processes.', safety:'safe', related:['top','kill'] },
  { name:'top', category:'monitoring', syntax:'top', examples:['top'], explanation:'Interactively monitor processes and resource usage.', warning:'Safe command.', safety:'safe', related:['ps','free'] },
  { name:'free', category:'monitoring', syntax:'free [options]', examples:['free -h'], explanation:'Show system memory usage.', warning:'Safe command.', safety:'safe', related:['top','vmstat'] },
  { name:'kill', category:'monitoring', syntax:'kill [signal] <pid>', examples:['kill 2410','kill -TERM 2410'], explanation:'Send a signal to a process.', warning:'Medium to high risk. Killing the wrong process can interrupt services or data writes.', safety:'high', related:['ps','pkill'] },
  { name:'uname', category:'monitoring', syntax:'uname [options]', examples:['uname -a','uname -r'], explanation:'Show kernel and system information.', warning:'Safe command.', safety:'safe', related:['hostname','lsb_release'] },
  { name:'hostname', category:'networking', syntax:'hostname', examples:['hostname'], explanation:'Show or, with privileges, change the system hostname.', warning:'Reading is safe; changing a hostname can affect networking and services.', safety:'medium', related:['uname','ip'] },
  { name:'ip', category:'networking', syntax:'ip <object> <command>', examples:['ip addr','ip route'], explanation:'Inspect and configure network interfaces, addresses and routes.', warning:'Viewing is safe. Changing routes or interfaces can disconnect a system.', safety:'medium', related:['ping','ss'] },
  { name:'ping', category:'networking', syntax:'ping [options] <host>', examples:['ping -c 4 1.1.1.1','ping -c 4 example.com'], explanation:'Test basic network reachability and latency.', warning:'Generally safe; avoid excessive traffic.', safety:'safe', related:['ip','curl'] },
  { name:'ss', category:'networking', syntax:'ss [options]', examples:['ss -tulpn','ss -tun'], explanation:'Inspect sockets and listening network services.', warning:'Safe command when inspecting.', safety:'safe', related:['ip','curl'] },
  { name:'curl', category:'networking', syntax:'curl [options] <url>', examples:['curl https://example.com','curl -I https://example.com'], explanation:'Transfer data to or from URLs and APIs.', warning:'Medium risk if piping unknown downloads into a shell or sending secrets.', safety:'medium', related:['wget','ping'] },
  { name:'wget', category:'networking', syntax:'wget [options] <url>', examples:['wget https://example.com/file.tar.gz'], explanation:'Download files over HTTP, HTTPS and FTP.', warning:'Medium risk: verify downloaded files before executing them.', safety:'medium', related:['curl','sha256sum'] },
  { name:'apt', category:'package management', syntax:'apt <command> [package]', examples:['sudo apt update','sudo apt install git'], explanation:'Manage packages on Debian and Ubuntu based systems.', warning:'High risk when installing, removing or upgrading system packages with sudo.', safety:'high', related:['dpkg','sudo'] },
  { name:'dnf', category:'package management', syntax:'dnf <command> [package]', examples:['sudo dnf install git','dnf search nginx'], explanation:'Manage packages on Fedora and related systems.', warning:'High risk for system-changing actions with sudo.', safety:'high', related:['rpm','sudo'] },
  { name:'pacman', category:'package management', syntax:'pacman <options> [package]', examples:['sudo pacman -Syu','sudo pacman -S git'], explanation:'Manage packages on Arch Linux and related systems.', warning:'High risk for system-changing actions with sudo.', safety:'high', related:['sudo'] },
  { name:'systemctl', category:'monitoring', syntax:'systemctl <action> <unit>', examples:['systemctl status ssh','sudo systemctl restart nginx'], explanation:'Inspect and control systemd services and units.', warning:'Viewing is safe. Starting, stopping or disabling important units can affect the system.', safety:'high', related:['journalctl','ps'] },
  { name:'journalctl', category:'monitoring', syntax:'journalctl [options]', examples:['journalctl -xe','journalctl -u nginx --since today'], explanation:'Read logs collected by systemd-journald.', warning:'Usually safe when reading logs; logs can contain sensitive data.', safety:'safe', related:['systemctl','tail'] },
  { name:'echo', category:'shell scripting', syntax:'echo [text]', examples:['echo Hello LinuxAid','echo $PATH'], explanation:'Print text or shell-expanded values.', warning:'Safe unless combined with redirection into important files.', safety:'safe', related:['printf','cat'] },
  { name:'printf', category:'shell scripting', syntax:'printf <format> [arguments]', examples:['printf "Hello %s\\n" Linux'], explanation:'Print formatted text predictably in scripts.', warning:'Safe command.', safety:'safe', related:['echo'] },
  { name:'history', category:'shell scripting', syntax:'history', examples:['history'], explanation:'Show recent shell commands.', warning:'Safe, but command history can reveal sensitive arguments.', safety:'safe', related:['grep'] },
  { name:'which', category:'shell scripting', syntax:'which <command>', examples:['which bash','which python3'], explanation:'Show which executable would be run for a command.', warning:'Safe command.', safety:'safe', related:['whereis','type'] },
  { name:'tar', category:'file management', syntax:'tar <options> <archive> [files]', examples:['tar -czf backup.tar.gz project/','tar -xzf backup.tar.gz'], explanation:'Create and extract tar archives.', warning:'Medium risk when extracting untrusted archives or overwriting files.', safety:'medium', related:['gzip','zip'] },
  { name:'ssh', category:'networking', syntax:'ssh [user@]host', examples:['ssh learner@server.example'], explanation:'Open an encrypted remote shell session.', warning:'Medium risk. Verify host identity and never expose private keys.', safety:'medium', related:['scp','ss'] },
  { name:'man', category:'shell scripting', syntax:'man <command>', examples:['man ls','man chmod'], explanation:'Open the manual page for a command.', warning:'Safe command.', safety:'safe', related:['help','which'] }
];

export function getCommand(name) {
  const needle = String(name || '').toLowerCase();
  return COMMAND_CATALOG.find(command => command.name === needle) || null;
}

export function commandNames() {
  return COMMAND_CATALOG.map(command => command.name);
}
