import { getSessionUser } from './authClientV5.js';
import { loadSocialPosts,createSocialPost,loadPostReplies,createReply,setReaction,toggleBookmark,reportContent,listPeople,loadSocialNotifications,markSocialNotificationRead } from './socialApi.js';

const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let user=await getSessionUser();let mode='latest';let currentTag='';let busy=false;
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const timeAgo=v=>{const d=new Date(v);const s=Math.floor((Date.now()-d)/1000);if(s<60)return'now';if(s<3600)return`${Math.floor(s/60)}m`;if(s<86400)return`${Math.floor(s/3600)}h`;if(s<604800)return`${Math.floor(s/86400)}d`;return d.toLocaleDateString()};
const avatar=(url,name)=>url?`<img class="social-avatar" src="${esc(url)}" alt="">`:`<div class="social-avatar">${esc((name||'L').slice(0,1).toUpperCase())}</div>`;
function toast(msg,type='ok'){const n=$('#socialNotice');if(!n)return;n.textContent=msg;n.dataset.type=type;n.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>n.hidden=true,4200)}
function requireUser(){if(user)return true;location.href='auth.html?next=community';return false}

async function renderPeople(){const box=$('#peopleMini');if(!box)return;try{const people=await listPeople('',5);box.innerHTML=people.length?people.map(p=>`<button class="chat-row person-mini" data-person="${p.id}">${avatar(p.avatarUrl,p.displayName)}<span class="chat-row-body"><strong>${esc(p.displayName)}</strong><span>${esc(p.rank)} • ${p.xp} XP</span></span></button>`).join(''):'<div class="social-empty">More members will appear as LinuxAid grows.</div>';box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>location.href=`people.html?user=${encodeURIComponent(b.dataset.person)}`)}catch(e){box.textContent='Could not load people.'}}
async function renderNotifications(){const box=$('#notifMini');if(!box||!user)return;try{const rows=await loadSocialNotifications(6);box.innerHTML=rows.length?rows.map(n=>`<button class="chat-row ${n.read_at?'':'unread'}" data-notif="${n.id}"><span class="chat-row-body"><strong>${esc(n.title)}</strong><span>${esc(n.body)} • ${timeAgo(n.created_at)}</span></span></button>`).join(''):'<div class="social-empty">No notifications yet.</div>';box.querySelectorAll('[data-notif]').forEach(b=>b.onclick=async()=>{await markSocialNotificationRead(b.dataset.notif);b.classList.remove('unread')})}catch(e){box.textContent='Notifications unavailable.'}}

function reactionLabel(type,count){const icon={like:'♥',helpful:'✓',insightful:'✦',solved:'★'}[type];return`${icon} ${count||0}`}
function card(post){const counts=post.reaction_counts||{};const tags=(post.tags||[]).map(t=>`<button class="social-tag" data-tag="${esc(t)}">#${esc(t)}</button>`).join('');return `<article class="social-card" data-post="${post.id}"><div class="social-author"><div class="social-avatar">${esc((post.author_name||'L').slice(0,1).toUpperCase())}</div><div class="social-author-meta"><strong>${esc(post.author_name||'LinuxAid learner')}</strong><span>${timeAgo(post.created_at)}${post.is_solved?' • solved':''}</span></div></div><h3>${esc(post.title)}</h3><div class="social-card-body">${esc(post.body)}</div>${tags?`<div class="social-tags">${tags}</div>`:''}<div class="social-actions"><button class="social-action ${post.myReaction==='helpful'?'active':''}" data-react="helpful">${reactionLabel('helpful',counts.helpful)}</button><button class="social-action ${post.myReaction==='insightful'?'active':''}" data-react="insightful">${reactionLabel('insightful',counts.insightful)}</button><button class="social-action ${post.myReaction==='like'?'active':''}" data-react="like">${reactionLabel('like',counts.like)}</button><button class="social-action" data-replies>💬 ${post.reply_count||0}</button><button class="social-action ${post.isBookmarked?'active':''}" data-bookmark>🔖 ${post.bookmark_count||0}</button><button class="social-action" data-report>•••</button></div></article>`}

async function renderFeed(){if(busy)return;busy=true;const feed=$('#communityFeed');if(feed)feed.innerHTML='<div class="social-empty">Loading live discussions…</div>';try{const posts=await loadSocialPosts({mode,tag:currentTag,limit:45});if(!feed)return;feed.innerHTML=posts.length?posts.map(card).join(''):'<div class="social-empty">No discussions here yet. Start one worth reading.</div>';feed.querySelectorAll('[data-post]').forEach(el=>wireCard(el,posts.find(p=>p.id===el.dataset.post)));$('#feedCount').textContent=String(posts.length)}catch(e){feed.innerHTML=`<div class="social-empty">Community could not load: ${esc(e.message)}</div>`}finally{busy=false}}
function wireCard(el,post){el.querySelectorAll('[data-react]').forEach(b=>b.onclick=async()=>{if(!requireUser())return;b.disabled=true;try{await setReaction(post.id,b.dataset.react);await renderFeed()}catch(e){toast(e.message,'error')}finally{b.disabled=false}});el.querySelector('[data-bookmark]').onclick=async()=>{if(!requireUser())return;try{await toggleBookmark(post.id);await renderFeed()}catch(e){toast(e.message,'error')}};el.querySelector('[data-replies]').onclick=()=>openReplies(post);el.querySelector('[data-report]').onclick=async()=>{if(!requireUser())return;const reason=prompt('Why are you reporting this post?');if(reason&&reason.trim().length>=3){try{await reportContent('post',post.id,reason);toast('Report sent. Thank you.')}catch(e){toast(e.message,'error')}}};el.querySelectorAll('[data-tag]').forEach(t=>t.onclick=()=>{currentTag=t.dataset.tag;$('#activeTag').textContent=`#${currentTag}`;renderFeed()})}

async function openReplies(post){const d=$('#replyDialog');$('#replyTitle').textContent=post.title;const list=$('#replyList');list.innerHTML='<div class="social-empty">Loading replies…</div>';d.showModal();try{const rows=await loadPostReplies(post.id);list.innerHTML=rows.length?rows.map(r=>`<div class="reply-item"><strong>${esc(r.author_name||'LinuxAid learner')}</strong><p>${esc(r.body)}</p><small>${timeAgo(r.created_at)}</small></div>`).join(''):'<div class="social-empty">No replies yet.</div>'}catch(e){list.textContent=e.message}const form=$('#replyForm');form.onsubmit=async ev=>{ev.preventDefault();if(!requireUser())return;const input=$('#replyBody');const body=input.value.trim();if(!body)return;try{await createReply(post.id,body);input.value='';toast('Reply posted');d.close();await openReplies(post);await renderFeed()}catch(e){toast(e.message,'error')}}}

$('#communityForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!requireUser())return;const title=$('#communityTitle').value.trim(),body=$('#communityBody').value.trim(),tags=$('#communityTags').value.split(',');if(title.length<8||body.length<20)return toast('Use a clearer title and enough detail.','error');const btn=e.submitter;btn.disabled=true;btn.textContent='Publishing…';try{await createSocialPost({title,body,tags});e.target.reset();toast('Discussion is live');mode='latest';await renderFeed()}catch(err){toast(err.message,'error')}finally{btn.disabled=false;btn.textContent='Publish'}});
$$('[data-feed-mode]').forEach(b=>b.onclick=()=>{const next=b.dataset.feedMode;if((next==='following'||next==='saved')&&!user){requireUser();return}$$('[data-feed-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=next;currentTag='';$('#activeTag').textContent='';renderFeed()});
$('#clearTag')?.addEventListener('click',()=>{currentTag='';$('#activeTag').textContent='';renderFeed()});
$('#replyClose')?.addEventListener('click',()=>$('#replyDialog').close());
$('#composeToggle')?.addEventListener('click',()=>$('#composerPanel').scrollIntoView({behavior:'smooth',block:'center'}));
if(!user){$('#communityForm button[type="submit"]').textContent='Sign in to publish'}
await Promise.all([renderFeed(),renderPeople(),renderNotifications()]);
