import { getSessionUser } from './authClientV5.js';
import { listConversations,loadMessages,sendMessage,getSocialClient,editMessage,deleteMessage } from './socialApi.js';
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let user=await getSessionUser();if(!user)location.href='auth.html?next=messages';let conversations=[];let activeId=new URLSearchParams(location.search).get('c')||'';let fallbackPoll=null;let liveChannel=null;let lastMessageKey='';let opening=false;
const time=v=>new Date(v).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
function avatar(c){return c.avatarUrl?`<img class="social-avatar" src="${esc(c.avatarUrl)}" alt="">`:`<div class="social-avatar">${esc((c.displayName||'L')[0])}</div>`}
function renderList(filter=''){const root=$('#conversationList');const rows=conversations.filter(c=>`${c.displayName} ${c.last_message_preview||''}`.toLowerCase().includes(filter.toLowerCase()));root.innerHTML=rows.length?rows.map(c=>`<button class="chat-row ${c.id===activeId?'active':''} ${c.unread?'unread':''}" data-id="${c.id}">${avatar(c)}<span class="chat-row-body"><strong>${esc(c.displayName)}</strong><span>${esc(c.last_message_preview||'No messages yet')}</span></span></button>`).join(''):'<div class="social-empty">No conversations yet. Open People and start one.</div>';root.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openConversation(b.dataset.id));$('#conversationCount').textContent=conversations.length;$('#unreadCount').textContent=conversations.filter(c=>c.unread).length}
async function refreshConversations(openCurrent=true){try{conversations=await listConversations();renderList($('#conversationSearch').value||'');if(activeId&&!conversations.some(c=>c.id===activeId))activeId='';if(!activeId&&conversations.length)activeId=conversations[0].id;if(openCurrent&&activeId)await openConversation(activeId,false)}catch(e){$('#conversationList').innerHTML=`<div class="social-empty">${esc(e.message)}</div>`}}
async function openConversation(id,push=true){if(opening)return;opening=true;try{activeId=id;const c=conversations.find(x=>x.id===id);if(push)history.replaceState(null,'',`messages.html?c=${encodeURIComponent(id)}`);renderList($('#conversationSearch').value||'');$('#chatPeer').innerHTML=`<strong>${esc(c?.displayName||'Conversation')}</strong><span>${c?.peers?.[0]?.availabilityStatus?esc(c.peers[0].availabilityStatus.replaceAll('-',' ')):c?.peers?.[0]?.rank?esc(c.peers[0].rank):'LinuxAid member'} • <span class="v8-live-dot">Live</span></span>`;const input=$('#messageBody'),btn=$('#messageForm button');input.disabled=false;btn.disabled=false;await refreshMessages(true);await subscribeConversation(id)}finally{opening=false}}
async function refreshMessages(force=false){if(!activeId)return;try{const rows=await loadMessages(activeId,100);const key=rows.map(r=>`${r.id}:${r.edited_at||''}:${r.deleted_at||''}`).join('|');if(!force&&key===lastMessageKey)return;lastMessageKey=key;const root=$('#liveMessages');root.innerHTML=rows.length?rows.map(m=>`<div class="chat-bubble ${m.mine?'mine':''}" data-message="${m.id}" data-mine="${m.mine?'1':'0'}"><span>${esc(m.body)}</span><time>${time(m.created_at)}${m.edited_at?' • edited':''}</time>${m.mine&&!m.deleted_at?'<div class="v8-message-tools"><button type="button" data-edit title="Edit message">Edit</button><button type="button" data-delete title="Delete message">Delete</button></div>':''}</div>`).join(''):'<div class="social-empty">No messages yet. Say hello without dropping your password. 🙂</div>';root.querySelectorAll('[data-message][data-mine="1"]').forEach(node=>{node.querySelector('[data-edit]')?.addEventListener('click',async()=>{const current=node.querySelector('span')?.textContent||'';const next=prompt('Edit your message:',current);if(next===null||!next.trim()||next.trim()===current)return;try{await editMessage(node.dataset.message,next.trim());await refreshMessages(true)}catch(e){alert(e.message)}});node.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(!confirm('Delete this message?'))return;try{await deleteMessage(node.dataset.message);await refreshMessages(true)}catch(e){alert(e.message)}})});root.scrollTop=root.scrollHeight;const c=conversations.find(x=>x.id===activeId);if(c)c.unread=false;renderList($('#conversationSearch').value||'')}catch(e){$('#liveMessages').innerHTML=`<div class="social-empty">${esc(e.message)}</div>`}}
async function subscribeConversation(id){const client=await getSocialClient();if(liveChannel){await client.removeChannel(liveChannel).catch(()=>{});liveChannel=null}liveChannel=client.channel(`linuxaid-messages-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},async()=>{await refreshMessages(false);await refreshConversations(false)}).subscribe(status=>{const dot=$('#chatPeer .v8-live-dot');if(dot)dot.textContent=status==='SUBSCRIBED'?'Live':'Connecting'})}
function startFallback(){clearInterval(fallbackPoll);fallbackPoll=setInterval(()=>{if(!document.hidden){refreshConversations(false);if(activeId)refreshMessages(false)}},60_000)}
$('#messageForm').addEventListener('submit',async e=>{e.preventDefault();if(!activeId)return;const input=$('#messageBody'),body=input.value.trim();if(!body)return;const btn=e.submitter;btn.disabled=true;try{await sendMessage(activeId,body);input.value='';await refreshMessages(true);await refreshConversations(false)}catch(err){alert(err.message)}finally{btn.disabled=false;input.focus()}});
$('#messageBody').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#messageForm').requestSubmit()}});$('#conversationSearch').addEventListener('input',e=>renderList(e.target.value));document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshConversations(false);if(activeId)refreshMessages(false)}});window.addEventListener('pagehide',async()=>{clearInterval(fallbackPoll);try{if(liveChannel)(await getSocialClient()).removeChannel(liveChannel)}catch{}},{once:true});startFallback();await refreshConversations();
