import { getSessionUser } from './authClientV5.js';
import { listPeople,toggleFollow,startDirectConversation } from './socialApi.js';
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let user=await getSessionUser();let timer=null;let cache=[];
const avatar=p=>p.avatarUrl?`<img class="social-avatar" src="${esc(p.avatarUrl)}" alt="">`:`<div class="social-avatar">${esc((p.displayName||'L')[0])}</div>`;
function chips(p){return [p.experienceLevel,p.availabilityStatus,p.preferredShell&&`${p.preferredShell} shell`,...(p.skills||[]).slice(0,4)].filter(Boolean).map(x=>`<span class="v8-chip">${esc(String(x).replaceAll('-',' '))}</span>`).join('')}
function card(p){return `<article class="person-card" data-id="${p.id}"><div class="person-head">${avatar(p)}<div class="social-author-meta"><strong>${esc(p.displayName)}</strong><span>${p.username?'@'+esc(p.username)+' • ':''}${esc(p.rank)} • ${p.xp} XP</span></div></div><p style="margin:0;color:var(--muted);line-height:1.55">${esc(p.headline||p.bio||'LinuxAid learner')}</p><div class="v8-chip-list">${chips(p)}</div><div style="display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:.78rem"><span>${p.followers} followers</span><span>${p.postCount} posts</span>${p.distro?`<span>${esc(p.distro)}</span>`:''}</div><div class="person-actions"><button class="button ${p.isFollowing?'':'primary'}" data-follow>${p.isFollowing?'Following':'Follow'}</button><button class="button" data-message>Message</button><button class="button" data-view>Profile</button></div></article>`}
async function render(q=''){const root=$('#peopleGrid');root.innerHTML='<div class="social-empty">Loading people…</div>';try{cache=await listPeople(q,48);root.innerHTML=cache.length?cache.map(card).join(''):'<div class="social-empty">No public profiles match this search yet.</div>';root.querySelectorAll('[data-id]').forEach(el=>wire(el,cache.find(x=>x.id===el.dataset.id)))}catch(e){root.innerHTML=`<div class="social-empty">${esc(e.message)}</div>`}}
function wire(el,p){el.querySelector('[data-follow]').onclick=async()=>{if(!user){location.href='auth.html?next=people';return}const b=el.querySelector('[data-follow]');b.disabled=true;try{p.isFollowing=await toggleFollow(p.id);await render($('#peopleSearch').value)}catch(e){alert(e.message)}finally{b.disabled=false}};el.querySelector('[data-message]').onclick=async()=>{if(!user){location.href='auth.html?next=people';return}try{const id=await startDirectConversation(p.id);location.href=`messages.html?c=${encodeURIComponent(id)}`}catch(e){alert(e.message)}};el.querySelector('[data-view]').onclick=()=>openProfile(p)}
function openProfile(p){const d=$('#personDialog'),box=$('#personDetail');const links=[p.websiteUrl&&`<a class="button" href="${esc(p.websiteUrl)}" target="_blank" rel="noopener noreferrer">Website</a>`,p.githubUrl&&`<a class="button" href="${esc(p.githubUrl)}" target="_blank" rel="noopener noreferrer">GitHub</a>`].filter(Boolean).join('');box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px"><div class="person-head">${avatar(p)}<div><h2 style="margin:0">${esc(p.displayName)}</h2><p style="margin:.3rem 0;color:var(--muted)">${p.username?'@'+esc(p.username)+' • ':''}${esc(p.rank)}</p></div></div><button class="button" id="personClose">Close</button></div><p style="font-size:1.02rem;line-height:1.75">${esc(p.bio||p.headline||'No public bio yet.')}</p><div class="v8-chip-list">${chips(p)}</div>${p.lookingFor?`<p><strong>Looking for:</strong> ${esc(p.lookingFor)}</p>`:''}<div class="social-statbar"><div class="social-stat"><strong>${p.xp}</strong><small>XP</small></div><div class="social-stat"><strong>${p.followers}</strong><small>followers</small></div><div class="social-stat"><strong>${p.postCount}</strong><small>posts</small></div></div><div class="person-actions" style="margin-top:14px">${links}<button class="button" id="personMessage">Message</button></div>`;d.showModal();$('#personClose').onclick=()=>d.close();$('#personMessage')?.addEventListener('click',async()=>{if(!user){location.href='auth.html?next=people';return}try{const id=await startDirectConversation(p.id);location.href=`messages.html?c=${encodeURIComponent(id)}`}catch(e){alert(e.message)}})}
$('#peopleSearch').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>render(e.target.value),260)});const initial=new URLSearchParams(location.search);await render(initial.get('q')||'');if(initial.get('user')){const target=cache.find(p=>p.id===initial.get('user'));if(target)openProfile(target)}
