import { getSessionUser } from './authClientV5.js';
import { listPeople,loadMySocialProfile,toggleFollow,startDirectConversation } from './socialApi.js';
const $=s=>document.querySelector(s);const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let user=await getSessionUser();let timer=null;let cache=[];let loaded=false;
const avatar=p=>p.avatarUrl?`<img class="social-avatar" src="${esc(p.avatarUrl)}" alt="">`:`<div class="social-avatar">${esc((p.displayName||'L')[0])}</div>`;
function card(p){const actions=p.isSelf?`<a class="button primary" href="profile.html">Edit profile</a><button class="button" data-view>Preview</button>`:`<button class="button ${p.isFollowing?'':'primary'}" data-follow>${p.isFollowing?'Following':'Follow'}</button><button class="button" data-message>Message</button><button class="button" data-view>Profile</button>`;return `<article class="person-card" data-id="${p.id}"><div class="person-head">${avatar(p)}<div class="social-author-meta"><strong>${esc(p.displayName)}${p.isSelf?' <span style="color:var(--green);font-size:.72rem">• You</span>':''}</strong><span>${p.username?'@'+esc(p.username)+' • ':''}${esc(p.rank)} • ${p.xp} XP</span></div></div><p style="margin:0;color:var(--muted);line-height:1.55">${esc(p.headline||p.bio||'LinuxAid learner')}</p><div style="display:flex;gap:12px;flex-wrap:wrap;color:var(--muted);font-size:.78rem"><span>${p.followers} followers</span><span>${p.postCount} posts</span>${p.distro?`<span>${esc(p.distro)}</span>`:''}</div><div class="person-actions">${actions}</div></article>`}
function matches(p,q){if(!q)return true;const hay=[p.displayName,p.username,p.headline,p.bio,p.distro,p.rank].join(' ').toLowerCase();return q.toLowerCase().trim().split(/\s+/).every(token=>hay.includes(token))}
function updateSummary(count,q=''){const el=$('#peopleSummary');if(!el)return;const others=cache.filter(p=>!p.isSelf).length;el.textContent=q?`${count} public profile${count===1?'':'s'} match “${q}”`:others?`${others} other public member${others===1?'':'s'} available`:'Your public profile is live • invite the next learner'}
function wireInvite(){const button=$('#invitePeople');if(!button)return;button.addEventListener('click',async()=>{const url=window.LINUXAID_CONFIG?.product?.website||location.origin+location.pathname.replace(/people\.html.*$/,'');try{await navigator.clipboard.writeText(url);button.textContent='Invite link copied ✓';setTimeout(()=>button.textContent='Copy invite link',1600)}catch{prompt('Share this LinuxAid link:',url)}})}
function renderRows(q=''){const root=$('#peopleGrid');const rows=cache.filter(p=>matches(p,q));updateSummary(rows.length,q);if(rows.length){const onlySelf=!q&&rows.length===1&&rows[0].isSelf;root.innerHTML=rows.map(card).join('')+(onlySelf?`<aside class="person-card invite-card"><div class="invite-icon"><i class="fas fa-user-plus"></i></div><strong>Bring the next Linux learner in.</strong><p style="margin:0;color:var(--muted);line-height:1.6">People discovery is live. Right now your profile is the only public member, so there is nobody else to return yet.</p><button class="button" id="invitePeople">Copy invite link</button></aside>`:'');root.querySelectorAll('[data-id]').forEach(el=>wire(el,rows.find(x=>x.id===el.dataset.id)));wireInvite();return}const onlyMember=loaded&&!q&&user;root.innerHTML=`<div class="discovery-empty" style="grid-column:1/-1"><i class="fas fa-user-group" style="font-size:1.6rem"></i><strong>${q?'No public profiles match that search yet.':onlyMember?'You are the first discoverable member here.':'No public profiles are discoverable yet.'}</strong><span>${q?'Try a shorter name, username, distro or skill.':onlyMember?'People discovery is working—there simply are no other public accounts yet. Invite someone and their profile will appear here automatically.':'Members appear here after they enable profile discovery.'}</span><div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:center"><a class="button primary" href="profile.html">Check my public profile</a>${onlyMember?'<button class="button" id="invitePeople">Copy invite link</button>':''}</div></div>`;wireInvite()}
async function load(){const root=$('#peopleGrid');root.innerHTML='<div class="social-empty">Loading people…</div>';try{const [others,mine]=await Promise.all([listPeople('',50),user?loadMySocialProfile().catch(()=>null):Promise.resolve(null)]);cache=mine?[{...mine,isSelf:true,isFollowing:false},...others]:others;loaded=true;renderRows($('#peopleSearch').value)}catch(e){root.innerHTML=`<div class="discovery-empty" style="grid-column:1/-1"><strong>People could not load.</strong><span>${esc(e.message||'Please try again.')}</span><button class="button" id="retryPeople">Retry</button></div>`;$('#retryPeople')?.addEventListener('click',load)}}
function wire(el,p){if(p.isSelf){el.querySelector('[data-view]')?.addEventListener('click',()=>openProfile(p));return}el.querySelector('[data-follow]').onclick=async()=>{if(!user){location.href='auth.html?next=people';return}const b=el.querySelector('[data-follow]');b.disabled=true;try{p.isFollowing=await toggleFollow(p.id);renderRows($('#peopleSearch').value)}catch(e){alert(e.message)}finally{b.disabled=false}};el.querySelector('[data-message]').onclick=async()=>{if(!user){location.href='auth.html?next=people';return}try{const id=await startDirectConversation(p.id);location.href=`messages.html?c=${encodeURIComponent(id)}`}catch(e){alert(e.message)}};el.querySelector('[data-view]').onclick=()=>openProfile(p)}
function openProfile(p){const d=$('#personDialog'),box=$('#personDetail');box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px"><div class="person-head">${avatar(p)}<div><h2 style="margin:0">${esc(p.displayName)}</h2><p style="margin:.3rem 0;color:var(--muted)">${p.username?'@'+esc(p.username)+' • ':''}${esc(p.rank)}</p></div></div><button class="button" id="personClose">Close</button></div><p style="font-size:1.02rem;line-height:1.75">${esc(p.bio||p.headline||'No public bio yet.')}</p><div class="social-statbar"><div class="social-stat"><strong>${p.xp}</strong><small>XP</small></div><div class="social-stat"><strong>${p.followers}</strong><small>followers</small></div><div class="social-stat"><strong>${p.postCount}</strong><small>posts</small></div></div>${p.distro?`<p style="color:var(--muted)">Primary distro: <strong>${esc(p.distro)}</strong></p>`:''}`;d.showModal();$('#personClose').onclick=()=>d.close()}
const initial=new URLSearchParams(location.search).get('q')||'';$('#peopleSearch').value=initial;
$('#peopleSearch').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>{const q=e.target.value.trim();const url=new URL(location.href);q?url.searchParams.set('q',q):url.searchParams.delete('q');history.replaceState(null,'',url);if(loaded)renderRows(q)},120)});await load();
