import {initBackend,getBackendStatus,onAuthStateChangedListener,loadUserProfile,saveUserProfile,uploadAvatar,touchPresence} from '../backend.js';
import {getProgressSummary,exportProgress,importProgress,resetProgress} from './progress.js';
import {LABS,readLearningState} from './learningData.js';
import {identifyAnalyticsUser,setAnalyticsOptOut,isAnalyticsOptedOut} from './analytics.js';
const config=window.LINUXAID_CONFIG||{};await initBackend(config);let currentUser=getBackendStatus().user||null;const $=id=>document.getElementById(id);
function stat(value,label){const e=document.createElement('div');e.className='stat-card';const s=document.createElement('strong');s.textContent=value;const l=document.createElement('span');l.textContent=label;e.append(s,l);return e;}
function renderProgress(){const p=getProgressSummary(),learning=readLearningState();$('profileStats')?.replaceChildren(stat(p.xp,'XP earned'),stat(p.learnedCommands.length,'Commands explored'),stat(p.streakDays,'Day streak'),stat(p.level,'Learner level'));const achievements=$('achievementGrid');if(achievements){achievements.replaceChildren();(p.achievements.length?p.achievements:['Run useful commands and complete labs to unlock milestones']).forEach(name=>{const b=document.createElement('span');b.className='chip';b.innerHTML='<i class="fas fa-medal"></i> ';b.append(document.createTextNode(name));achievements.appendChild(b);});}const map=$('skillMap');if(map){map.replaceChildren();const rows=[['Beginner commands',p.roadmap.beginner],['Intermediate commands',p.roadmap.intermediate],['Advanced commands',p.roadmap.advanced],['Hands-on labs',Math.round((learning.completedLabs.length/Math.max(1,LABS.length))*100)]];rows.forEach(([label,value])=>{const row=document.createElement('div');row.style.marginBottom='16px';const head=document.createElement('div');head.style.cssText='display:flex;justify-content:space-between;gap:12px;margin-bottom:7px';head.innerHTML=`<span>${label}</span><strong>${value}%</strong>`;const bar=document.createElement('div');bar.className='course-progress';const fill=document.createElement('span');fill.style.width=`${Math.min(100,value)}%`;bar.appendChild(fill);row.append(head,bar);map.appendChild(row);});}}
function renderIdentity(profile={}){const name=profile.displayName||currentUser?.displayName||'LinuxAid Learner',avatar=profile.avatarUrl||currentUser?.avatarUrl||'';$('profileName').textContent=name;$('profileRole').textContent=profile.role||'learner';$('profileHandle').textContent=profile.username?'@'+profile.username:(profile.headline||currentUser?.email||'');$('profileBio').textContent=profile.bio||profile.headline||'Add a short bio so people know what you are learning.';$('profileFollowers').textContent=profile.followerCount||0;$('profileFollowing').textContent=profile.followingCount||0;$('profilePosts').textContent=profile.postCount||0;const orb=$('profileAvatar');orb.replaceChildren();if(avatar){const img=document.createElement('img');img.src=avatar;img.alt='';orb.appendChild(img);}else orb.textContent=(name[0]||'L').toUpperCase();$('profileDisplayName').value=name;$('profileUsername').value=profile.username||'';$('profileHeadline').value=profile.headline||'';$('profileBioInput').value=profile.bio||'';$('profileDistro').value=profile.distro||'';$('profileGoal').value=profile.learningGoal||'';$('profilePublic').checked=profile.isPublic!==false;identifyAnalyticsUser(currentUser,profile);}
async function handleAuth(user){currentUser=user||null;const form=$('profileForm');if(!currentUser){renderIdentity({});$('syncStatus').innerHTML='Sign in to edit your public LinuxAid profile. <a href="auth.html?next=profile">Sign in</a>';form?.querySelectorAll('input,textarea,select,button').forEach(x=>x.disabled=true);return;}form?.querySelectorAll('input,textarea,select,button').forEach(x=>x.disabled=false);try{await touchPresence();const profile=await loadUserProfile(currentUser.uid);renderIdentity(profile||{displayName:currentUser.displayName});$('syncStatus').textContent='Synced with Supabase ✓';}catch(e){console.error(e);$('syncStatus').textContent='Profile sync issue — try again in a moment.';}}
$('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return location.href='auth.html?next=profile';const profile={displayName:$('profileDisplayName').value.trim(),username:$('profileUsername').value.trim(),headline:$('profileHeadline').value.trim(),bio:$('profileBioInput').value.trim(),distro:$('profileDistro').value,learningGoal:$('profileGoal').value.trim(),isPublic:$('profilePublic').checked,avatarUrl:(await loadUserProfile(currentUser.uid).catch(()=>null))?.avatarUrl||''};const b=e.submitter;b.disabled=true;b.textContent='Saving…';try{await saveUserProfile(currentUser.uid,profile);const fresh=await loadUserProfile(currentUser.uid);renderIdentity(fresh||profile);$('syncStatus').textContent='Profile saved and synced ✓';b.textContent='Saved ✓';}catch(err){$('syncStatus').textContent=err.message||'Could not save profile.';b.textContent='Save profile';}finally{setTimeout(()=>{b.disabled=false;b.textContent='Save profile';},850);}});
$('avatarUpload')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file||!currentUser)return;const s=$('avatarStatus');s.textContent='Uploading…';try{await uploadAvatar(file);renderIdentity(await loadUserProfile(currentUser.uid));s.textContent='Profile picture updated ✓';}catch(err){s.textContent=err.message||'Upload failed.';}finally{e.target.value='';}});
$('exportProgress')?.addEventListener('click',()=>{const payload={...exportProgress(),learning:readLearningState()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`linuxaid-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});$('importProgress')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());importProgress(payload);if(payload.learning)localStorage.setItem('linuxaid-learning-v1',JSON.stringify(payload.learning));location.reload();}catch(err){alert(`Could not import LinuxAid progress: ${err.message}`);}});$('resetProgress')?.addEventListener('click',()=>{if(!confirm('Reset local LinuxAid command and lab progress on this browser?'))return;resetProgress();localStorage.removeItem('linuxaid-learning-v1');renderProgress();});const analytics=$('analyticsOptOut');if(analytics){analytics.checked=!isAnalyticsOptedOut();analytics.addEventListener('change',()=>setAnalyticsOptOut(!analytics.checked));}
document.addEventListener('linuxaid:state-synced',()=>{renderProgress();if($('syncStatus'))$('syncStatus').textContent='Learning state synced ✓';});renderProgress();renderIdentity({});onAuthStateChangedListener(handleAuth);if(currentUser)handleAuth(currentUser);
