import { getAuthClient, getSessionUser } from './authClientV5.js';

const cap=(n,min,max)=>Math.min(max,Math.max(min,n));
const text=(v,max)=>String(v||'').trim().slice(0,max);
const mapProfile=p=>({id:p.id,displayName:p.display_name||p.username||'LinuxAid learner',username:p.username||'',headline:p.headline||'',bio:p.bio||'',avatarUrl:p.avatar_url||'',distro:p.distro||'',followers:p.follower_count||0,following:p.following_count||0,xp:p.xp||0,rank:p.rank_name||'Kernel Seed',lastActive:p.last_active_at||null,postCount:p.post_count||0,experienceLevel:p.experience_level||'beginner',preferredShell:p.preferred_shell||'bash',favoriteEditor:p.favorite_editor||'',skills:Array.isArray(p.skills)?p.skills:[],lookingFor:p.looking_for||'',websiteUrl:p.website_url||'',githubUrl:p.github_url||'',availabilityStatus:p.availability_status||'learning'});

async function ctx(){const client=await getAuthClient();const user=await getSessionUser();return{client,user,userId:user?.id||null};}
export async function getSocialClient(){return getAuthClient()}

export async function loadMySocialProfile(){const {client,userId}=await ctx();if(!userId)return null;const {data,error}=await client.from('profiles').select('*').eq('id',userId).maybeSingle();if(error)throw error;return data?mapProfile(data):null;}

export async function listPeople(query='',limit=30){const {client,userId}=await ctx();let q=client.from('profiles').select('id,display_name,username,headline,bio,avatar_url,distro,follower_count,following_count,xp,rank_name,last_active_at,post_count,experience_level,preferred_shell,favorite_editor,skills,looking_for,website_url,github_url,availability_status').eq('is_public',true).order('last_active_at',{ascending:false}).limit(cap(limit,1,50));const term=text(query,80);if(term){const clean=term.replace(/[%,]/g,'');q=q.or(`display_name.ilike.%${clean}%,username.ilike.%${clean}%,headline.ilike.%${clean}%`)}const {data,error}=await q;if(error)throw error;const people=(data||[]).filter(p=>p.id!==userId).map(mapProfile);let following=new Set();if(userId&&people.length){const {data:f,error:fe}=await client.from('follows').select('following_id').eq('follower_id',userId).in('following_id',people.map(p=>p.id));if(fe)throw fe;following=new Set((f||[]).map(x=>x.following_id))}return people.map(p=>({...p,isFollowing:following.has(p.id)}))}

export async function toggleFollow(targetId){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to follow people.');if(targetId===userId)throw new Error('You cannot follow yourself.');const {data,error}=await client.from('follows').select('following_id').eq('follower_id',userId).eq('following_id',targetId).maybeSingle();if(error)throw error;if(data){const {error:e}=await client.from('follows').delete().eq('follower_id',userId).eq('following_id',targetId);if(e)throw e;return false}const {error:e}=await client.from('follows').insert({follower_id:userId,following_id:targetId});if(e)throw e;return true}
export async function blockUser(targetId){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in first.');if(!targetId||targetId===userId)throw new Error('Invalid user.');const {error}=await client.from('user_blocks').upsert({blocker_id:userId,blocked_id:targetId},{onConflict:'blocker_id,blocked_id'});if(error)throw error;return true}
export async function unblockUser(targetId){const {client,userId}=await ctx();if(!userId)return false;const {error}=await client.from('user_blocks').delete().eq('blocker_id',userId).eq('blocked_id',targetId);if(error)throw error;return true}

export async function loadSocialPosts({mode='latest',tag='',limit=40}={}){const {client,userId}=await ctx();let q=client.from('community_posts').select('id,author_id,author_name,title,body,tags,is_solved,reaction_counts,bookmark_count,upvotes_count,reply_count,created_at,updated_at,post_type,distro,code_snippet').order(mode==='active'?'updated_at':'created_at',{ascending:false}).limit(cap(limit,1,60));if(tag)q=q.contains('tags',[text(tag,30)]);if(mode==='following'&&userId){const {data:f,error:fe}=await client.from('follows').select('following_id').eq('follower_id',userId);if(fe)throw fe;const ids=(f||[]).map(x=>x.following_id);if(!ids.length)return[];q=q.in('author_id',ids)}if(mode==='saved'&&userId){const {data:b,error:be}=await client.from('community_bookmarks').select('post_id').eq('user_id',userId);if(be)throw be;const ids=(b||[]).map(x=>x.post_id);if(!ids.length)return[];q=q.in('id',ids)}const {data,error}=await q;if(error)throw error;const posts=data||[];if(!userId||!posts.length)return posts.map(p=>({...p,myReaction:null,isBookmarked:false}));const ids=posts.map(p=>p.id);const [{data:reactions,error:re},{data:bookmarks,error:be}]=await Promise.all([client.from('community_reactions').select('post_id,reaction').eq('user_id',userId).in('post_id',ids),client.from('community_bookmarks').select('post_id').eq('user_id',userId).in('post_id',ids)]);if(re)throw re;if(be)throw be;const rm=new Map((reactions||[]).map(x=>[x.post_id,x.reaction]));const bm=new Set((bookmarks||[]).map(x=>x.post_id));return posts.map(p=>({...p,myReaction:rm.get(p.id)||null,isBookmarked:bm.has(p.id)}))}

export async function createSocialPost({title,body,tags=[],postType='question',distro='',codeSnippet=''}){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to post.');const cleanTags=[...new Set((Array.isArray(tags)?tags:[]).map(t=>text(t.toLowerCase().replace(/[^a-z0-9-]/g,''),30)).filter(Boolean))].slice(0,5);const allowed=new Set(['question','tip','project','showcase','discussion']);const payload={author_id:userId,title:text(title,160),body:text(body,8000),tags:cleanTags,post_type:allowed.has(postType)?postType:'question',distro:text(distro,40),code_snippet:text(codeSnippet,12000)};const {data,error}=await client.from('community_posts').insert(payload).select('id').single();if(error)throwFriendlyRate(error);return data}
export async function updateSocialPost(postId,changes={}){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in first.');const payload={};if(changes.title!==undefined)payload.title=text(changes.title,160);if(changes.body!==undefined)payload.body=text(changes.body,8000);if(changes.codeSnippet!==undefined)payload.code_snippet=text(changes.codeSnippet,12000);if(changes.isSolved!==undefined)payload.is_solved=Boolean(changes.isSolved);payload.updated_at=new Date().toISOString();const {error}=await client.from('community_posts').update(payload).eq('id',postId).eq('author_id',userId);if(error)throw error;return true}
export async function deleteSocialPost(postId){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in first.');const {error}=await client.from('community_posts').delete().eq('id',postId).eq('author_id',userId);if(error)throw error;return true}

export async function loadPostReplies(postId){const {client}=await ctx();const {data,error}=await client.from('community_replies').select('id,post_id,author_id,author_name,body,created_at,updated_at').eq('post_id',postId).order('created_at',{ascending:true}).limit(100);if(error)throw error;return data||[]}
export async function createReply(postId,body){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to reply.');const {data,error}=await client.from('community_replies').insert({post_id:postId,author_id:userId,body:text(body,5000)}).select('id').single();if(error)throwFriendlyRate(error);return data}

export async function setReaction(postId,reaction){const allowed=new Set(['like','helpful','insightful','solved']);if(!allowed.has(reaction))throw new Error('Unsupported reaction.');const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to react.');const {data,error}=await client.from('community_reactions').select('reaction').eq('post_id',postId).eq('user_id',userId).maybeSingle();if(error)throw error;if(data?.reaction===reaction){const {error:e}=await client.from('community_reactions').delete().eq('post_id',postId).eq('user_id',userId);if(e)throw e;return null}const {error:e}=await client.from('community_reactions').upsert({post_id:postId,user_id:userId,reaction},{onConflict:'post_id,user_id'});if(e)throw e;return reaction}
export async function toggleBookmark(postId){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to save posts.');const {data,error}=await client.from('community_bookmarks').select('post_id').eq('user_id',userId).eq('post_id',postId).maybeSingle();if(error)throw error;if(data){const {error:e}=await client.from('community_bookmarks').delete().eq('user_id',userId).eq('post_id',postId);if(e)throw e;return false}const {error:e}=await client.from('community_bookmarks').insert({user_id:userId,post_id:postId});if(e)throw e;return true}
export async function reportContent(targetType,targetId,reason){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to report content.');const {error}=await client.from('content_reports').insert({reporter_id:userId,target_type:targetType,target_id:targetId,reason:text(reason,500)});if(error)throw error;return true}

export async function startDirectConversation(targetUser){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to message people.');const {data,error}=await client.rpc('linuxaid_start_direct_conversation',{target_user:targetUser});if(error)throw error;return data}
export async function listConversations(){const {client,userId}=await ctx();if(!userId)return[];const {data:memberships,error:me}=await client.from('conversation_members').select('conversation_id,last_read_at').eq('user_id',userId);if(me)throw me;if(!memberships?.length)return[];const ids=memberships.map(x=>x.conversation_id);const {data:conversations,error:ce}=await client.from('conversations').select('id,title,is_group,last_message_at,last_message_preview,last_sender_id,created_at').in('id',ids).order('last_message_at',{ascending:false});if(ce)throw ce;const {data:allMembers,error:ae}=await client.from('conversation_members').select('conversation_id,user_id').in('conversation_id',ids);if(ae)throw ae;const peerIds=[...new Set((allMembers||[]).map(x=>x.user_id).filter(id=>id!==userId))];let profileMap=new Map();if(peerIds.length){const {data:profiles,error:pe}=await client.from('profiles').select('id,display_name,username,avatar_url,rank_name,availability_status').in('id',peerIds);if(pe)throw pe;profileMap=new Map((profiles||[]).map(p=>[p.id,mapProfile(p)]))}const readMap=new Map(memberships.map(m=>[m.conversation_id,m.last_read_at]));return (conversations||[]).map(c=>{const peers=(allMembers||[]).filter(m=>m.conversation_id===c.id&&m.user_id!==userId).map(m=>profileMap.get(m.user_id)).filter(Boolean);const lastRead=readMap.get(c.id);return{...c,peers,displayName:c.is_group?(c.title||'Group'):peers[0]?.displayName||'LinuxAid learner',avatarUrl:peers[0]?.avatarUrl||'',unread:Boolean(c.last_message_at&&(!lastRead||new Date(c.last_message_at)>new Date(lastRead))&&c.last_sender_id!==userId)}})}
export async function loadMessages(conversationId,limit=80){const {client,userId}=await ctx();if(!userId)return[];const {data,error}=await client.from('messages').select('id,conversation_id,sender_id,body,created_at,edited_at,deleted_at').eq('conversation_id',conversationId).order('created_at',{ascending:true}).limit(cap(limit,1,120));if(error)throw error;await client.rpc('linuxaid_mark_conversation_read',{target_conversation:conversationId});return (data||[]).map(m=>({...m,mine:m.sender_id===userId,body:m.deleted_at?'Message deleted':m.body}))}
export async function sendMessage(conversationId,body){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in to send messages.');const clean=text(body,4000);if(!clean)throw new Error('Write a message first.');const {data,error}=await client.from('messages').insert({conversation_id:conversationId,sender_id:userId,body:clean}).select('id,created_at').single();if(error)throwFriendlyRate(error);return data}
export async function editMessage(messageId,body){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in first.');const clean=text(body,4000);if(!clean)throw new Error('Message cannot be empty.');const {error}=await client.from('messages').update({body:clean,edited_at:new Date().toISOString()}).eq('id',messageId).eq('sender_id',userId).is('deleted_at',null);if(error)throw error;return true}
export async function deleteMessage(messageId){const {client,userId}=await ctx();if(!userId)throw new Error('Sign in first.');const {error}=await client.from('messages').update({deleted_at:new Date().toISOString(),body:'[deleted]'}).eq('id',messageId).eq('sender_id',userId);if(error)throw error;return true}

export async function loadSocialNotifications(limit=30){const {client,userId}=await ctx();if(!userId)return[];const {data,error}=await client.from('notifications').select('id,type,title,body,metadata,read_at,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(cap(limit,1,50));if(error)throw error;return data||[]}
export async function markSocialNotificationRead(id){const {client,userId}=await ctx();if(!userId)return;const {error}=await client.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',userId);if(error)throw error}

function throwFriendlyRate(error){const msg=String(error?.message||'');if(msg.includes('RATE_LIMIT_POSTS'))throw new Error('You are posting too quickly. Try again in a few minutes.');if(msg.includes('RATE_LIMIT_REPLIES'))throw new Error('You are replying too quickly. Slow down for a moment.');if(msg.includes('RATE_LIMIT_MESSAGES'))throw new Error('Too many messages at once. Try again shortly.');throw error}
