import {initBackend,getBackendStatus,invokeBackendFunction} from './backend.js';
import {COMMAND_CATALOG} from './js/commandCatalog.js';
import {analyzeLinuxCommand,interpretLinuxError} from './js/linuxTools.js';

const SYSTEM_PROMPT=`You are LinuxAid, a beginner-friendly Linux tutor. Explain concepts step by step, prefer safe read-only inspection before system changes, clearly warn before privileged or destructive commands, distinguish distro-specific commands, and never pretend a simulated command changed a real machine.`;
const aiConfig=(config={})=>config.ai||{};
const normalizeHistory=(history=[])=>(Array.isArray(history)?history:[]).filter(i=>i&&['user','assistant'].includes(i.role)&&i.text).slice(-10).map(i=>({role:i.role,content:String(i.text).slice(0,4000)}));
const readAnswer=result=>String(result?.answer||result?.output_text||result?.choices?.[0]?.message?.content||result?.choices?.[0]?.text||result?.candidates?.[0]?.content?.parts?.map(p=>p?.text||'').join('')||'').trim();

async function queryBackendFunction(prompt,config,history){await initBackend(config);const status=getBackendStatus();if(!status.ready||status.provider!=='supabase')throw new Error('Supabase backend is not configured.');const result=await invokeBackendFunction(aiConfig(config).edgeFunction||'linuxaid-ai',{prompt:String(prompt).slice(0,6000),history:normalizeHistory(history)});const answer=readAnswer(result);if(!answer)throw new Error('LinuxAid AI returned an empty answer.');return answer;}
async function queryProxy(prompt,config,history){const proxyUrl=aiConfig(config).proxyUrl||config.aiProxyUrl;if(!proxyUrl)throw new Error('LinuxAid AI proxy is not configured.');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),Number(aiConfig(config).requestTimeoutMs||25000));try{const response=await fetch(proxyUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:String(prompt).slice(0,6000),history:normalizeHistory(history)}),signal:controller.signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error?.message||result?.error||`AI proxy request failed (${response.status}).`);const answer=readAnswer(result);if(!answer)throw new Error('AI proxy returned an empty answer.');return answer;}finally{clearTimeout(timeout);}}

function commandToken(text){const cleaned=String(text||'').replace(/[`$]/g,' ').trim();const match=cleaned.match(/(?:^|\s)([a-zA-Z0-9_.+-]{2,})(?:\s|$)/g)||[];const names=new Set(COMMAND_CATALOG.map(c=>c.name));for(const raw of match){const token=raw.trim().toLowerCase();if(names.has(token))return token;}return'';}
function localTutor(prompt){const text=String(prompt||'').trim();const lower=text.toLowerCase();const prefix='**Local LinuxAid guide** — remote AI is unavailable, so this answer uses LinuxAid’s built-in Linux knowledge.\n\n';
  if(!text)return prefix+'Ask about a Linux command, error, permission, service, network problem or package workflow.';
  const error=interpretLinuxError(text);if(error.title!=='Unrecognized error pattern'&&error.title!=='No error entered')return prefix+`### ${error.title}\n${error.cause}\n\n**Check first**\n${error.checks.map(c=>`- \`${c}\``).join('\n')}\n\n**Safer next step**\n${error.fix}`;
  const token=commandToken(text);const cmd=COMMAND_CATALOG.find(c=>c.name===token);
  if(cmd){const risk=analyzeLinuxCommand(cmd.examples?.[0]||cmd.syntax||cmd.name);return prefix+`### \`${cmd.name}\`\n${cmd.explanation}\n\n**Syntax:** \`${cmd.syntax}\`\n${cmd.examples?.length?`\n**Examples**\n${cmd.examples.slice(0,3).map(x=>`- \`${x}\``).join('\n')}`:''}\n\n**Safety:** ${risk.title}. ${risk.summary}${cmd.related?.length?`\n\nRelated: ${cmd.related.slice(0,6).map(x=>`\`${x}\``).join(', ')}`:''}`;}
  if(/permission|chmod|chown|owner|group/.test(lower))return prefix+'For permission problems, inspect before changing anything:\n\n- `id` — confirm the current user and groups\n- `ls -l <path>` — inspect owner/group/mode\n- `namei -l <path>` — inspect every directory in a path\n\nAvoid jumping straight to `chmod 777` or `sudo`. Use the smallest permission change that actually solves the problem.';
  if(/network|dns|internet|connection|port/.test(lower))return prefix+'A safe network troubleshooting order is:\n\n1. `ip addr` — interface/address\n2. `ip route` — default route\n3. `ping -c 2 1.1.1.1` — basic IP reachability\n4. `getent hosts example.com` — DNS\n5. `ss -tulpn` — listening ports\n\nThis separates link/routing problems from DNS and service problems.';
  if(/service|systemctl|journal|daemon/.test(lower))return prefix+'Start with read-only service inspection:\n\n- `systemctl status <service>`\n- `journalctl -u <service> --since today`\n- `ss -tulpn` if the service should listen on a port\n\nUnderstand the failure before restarting or changing configuration.';
  if(/apt|dnf|pacman|package|install/.test(lower))return prefix+'First identify the distro with `cat /etc/os-release`. Debian/Ubuntu normally use `apt`, Fedora/RHEL use `dnf`, and Arch uses `pacman`. Search/inspect before adding third-party repositories or piping downloads into a shell.';
  return prefix+'I can still help locally with Linux commands, permissions, services, networking, package managers and common terminal errors. Include your distro, the command you ran, the exact output/error and what you expected to happen for a more useful answer.';
}

export function getAIStatus(config={}){const ai=aiConfig(config),backend=getBackendStatus();const supabaseConfigured=Boolean(config.backend?.supabase?.url&&(config.backend?.supabase?.publishableKey||config.backend?.supabase?.anonKey));if((backend.ready&&backend.provider==='supabase')||supabaseConfigured)return{ready:true,mode:'edge-function-with-local-fallback',provider:'supabase',function:ai.edgeFunction||'linuxaid-ai'};if(ai.proxyUrl||config.aiProxyUrl)return{ready:true,mode:'proxy-with-local-fallback',provider:ai.provider||'server'};return{ready:true,mode:'local',provider:'local'};}

export async function queryAI(prompt,config={},history=[]){const ai=aiConfig(config);const supabaseConfigured=Boolean(config.backend?.supabase?.url&&(config.backend?.supabase?.publishableKey||config.backend?.supabase?.anonKey));if(supabaseConfigured){try{return await queryBackendFunction(prompt,config,history);}catch(error){console.warn('LinuxAid remote tutor unavailable; using local guidance:',error?.message||error);return localTutor(prompt);}}if(ai.proxyUrl||config.aiProxyUrl){try{return await queryProxy(prompt,config,history);}catch(error){console.warn('LinuxAid AI proxy unavailable; using local guidance:',error?.message||error);return localTutor(prompt);}}return localTutor(prompt);}
export const queryGemini=queryAI;
export {localTutor};
